/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Cs
 */
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
public class ViewBill extends javax.swing.JFrame  {

    /**
     * Creates new form ViewBill
     */
    Statement st;
Connection con=null;
ResultSet rs=null;
PreparedStatement pst=null;
    public ViewBill() {
        initComponents();
        re.getCon();
        
    }
    public void UpdateTable()
    {
        try{
          con=re.getCon();
          Integer a2=Integer.parseInt(jTextField2.getText());
          String sql = "SELECT Item_No,Item_Name,Item_Make,Unit_Price,Unit_Quantity,Total FROM Item_Sol where Bill_no='"+a2+"'";
          pst=con.prepareStatement(sql);
          rs=pst.executeQuery();
          jTable1.setModel(DbUtils.resultSetToTableModel(rs));
          con.close();
        }
       catch(Exception e){
           
       }
       
    }
    


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        gstin = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cust = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tp = new javax.swing.JTextField();
        totl = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        billto = new javax.swing.JTextField();
        subtot = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tax = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(240, 240, 240));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("BILL TO");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 160, 80, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("TAX");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(840, 500, 40, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("TOTAL");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(840, 550, 58, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(460, 530, 90, 40);

        gstin.setEditable(false);
        gstin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(gstin);
        gstin.setBounds(560, 80, 180, 35);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(jTextField2);
        jTextField2.setBounds(140, 90, 60, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Billing Management System");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(340, 10, 520, 50);

        cust.setEditable(false);
        cust.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(cust);
        cust.setBounds(560, 160, 180, 35);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Invoice No.");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 90, 110, 30);

        tp.setEditable(false);
        tp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(tp);
        tp.setBounds(960, 490, 40, 40);

        totl.setEditable(false);
        totl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        totl.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(totl);
        totl.setBounds(960, 540, 180, 40);

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 270, 1170, 170);

        billto.setEditable(false);
        billto.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(billto);
        billto.setBounds(120, 160, 260, 40);

        subtot.setEditable(false);
        subtot.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(subtot);
        subtot.setBounds(960, 440, 180, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setText("Retrive");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(210, 90, 100, 30);

        tax.setEditable(false);
        tax.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(tax);
        tax.setBounds(1020, 490, 120, 40);

        contact.setEditable(false);
        contact.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(contact);
        contact.setBounds(930, 160, 180, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("DATE");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(870, 80, 50, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("GSTIN_NO.");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(450, 80, 110, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("SUB_TOTAL");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(840, 450, 110, 30);

        txtdate.setEditable(false);
        txtdate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(txtdate);
        txtdate.setBounds(930, 80, 180, 35);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("CONTACT NO.");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(800, 160, 130, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("CUST_NO.");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(460, 160, 100, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("LIST OF PRODUCT BOUGHT");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(340, 220, 520, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(560, 530, 90, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1190, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
    con=re.getCon();
            Integer a1=Integer.parseInt(jTextField2.getText());
           st= con.createStatement();
            rs=st.executeQuery("SELECT * FROM Billinfo where Bill_no='"+a1+"'");
            if(rs.next())
            {
                 cust.setText(rs.getString(2));
            billto.setText(rs.getString(3));
             txtdate.setText(rs.getString(5));
            contact.setText(rs.getString(6));
            gstin.setText(rs.getString(7));
            subtot.setText(rs.getString(9));
            tp.setText(rs.getString(10));
            tax.setText(rs.getString(11));
            totl.setText(rs.getString(12));
            con.close();
        UpdateTable();
            }
            else
                JOptionPane.showMessageDialog(null,"Incorrect Invoice No.");
               
             //rs.close();
            //pst.close();
           // 
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null,"Unable to Search");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
PrinterJob job=PrinterJob.getPrinterJob();
job.setJobName("Print Data");
job.setPrintable(new Printable(){
    public int print(Graphics pg,PageFormat pf , int pageNum){
        if(pageNum>0){
            return Printable.NO_SUCH_PAGE;
        }
        Graphics2D g2 = (Graphics2D)pg;
        g2.translate(pf.getImageableX(),pf.getImageableY());
        g2.scale(0.5,1.3);
        
        jPanel1.paint(g2);
       // jTextField2.paint(g2);
        return Printable.PAGE_EXISTS;
    }
});
boolean ok = job.printDialog();
if(ok){
    try{
        job.print();
    }
    catch (PrinterException ex){
        
    }
}

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField billto;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField cust;
    private javax.swing.JTextField gstin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField subtot;
    private javax.swing.JTextField tax;
    private javax.swing.JTextField totl;
    private javax.swing.JTextField tp;
    private javax.swing.JTextField txtdate;
    // End of variables declaration//GEN-END:variables

    private TableModel buildTableModel(ResultSet rs) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
